### ISSUE TITLE
Not able to perform tutorial

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [Christensen-Lab-Dartmouth/MethylNet#13]
Dear master,
I try to use the docker version and I'm not able to perform the tutorial.
Any help on this:
```
pymethyl-preprocess download_geo -g GSE42861
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE42nnn/GSE42861/suppl//GSE42861_RAW.tar?tool=geoquery'

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Content type 'application/x-tar'
  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  length 6166384640 bytes (5880.7 MB)

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: =
  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: downloaded 5880.7 MB


  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE42nnn/GSE42861/suppl//GSE42861_Readme.txt?tool=geoquery'

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Content type 'text/plain'
  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  length 128 bytes

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: downloaded 128 bytes


  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE42nnn/GSE42861/suppl//GSE42861_methylation_signal_matrix.txt.gz?tool=geoquery'

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Content type 'application/x-gzip'
  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  length 2760138123 bytes (2632.3 MB)

  warnings.warn(x, RRuntimeWarning)


/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: downloaded 2632.3 MB


  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE42nnn/GSE42861/suppl//GSE42861_methylation_signal_matrix_SUBSETS.tar.gz?tool=geoquery'

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  length 2796169000 bytes (2666.6 MB)

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: downloaded 2666.6 MB


  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE42nnn/GSE42861/suppl//GSE42861_non-methylated_signal_matrix.txt.gz?tool=geoquery'

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  length 2758508381 bytes (2630.7 MB)

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: downloaded 2630.7 MB


  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE42nnn/GSE42861/suppl//GSE42861_non-methylated_signal_matrix_SUBSETS.tar.gz?tool=geoquery'

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning:  length 2794369077 bytes (2664.9 MB)

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: downloaded 431.8 MB


  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: Error in download.file(paste(file.path(url, i), "tool=geoquery", sep = "?"),  : 
  download from 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE42nnn/GSE42861/suppl//GSE42861_non-methylated_signal_matrix_SUBSETS.tar.gz?tool=geoquery' failed

  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: In addition: 
  warnings.warn(x, RRuntimeWarning)
/usr/local/lib/python3.6/dist-packages/rpy2/rinterface/__init__.py:146: RRuntimeWarning: There were 27 warnings (use warnings() to see them)
  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/bin/pymethyl-preprocess", line 10, in <module>
    sys.exit(preprocess())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pymethylprocess/preprocess.py", line 45, in download_geo
    downloader.download_geo(geo_query,output_dir)
  File "/usr/local/lib/python3.6/dist-packages/pymethylprocess/PreProcessDataTypes.py", line 101, in download_geo
    geo.getGEOSuppFiles(query)
  File "/usr/local/lib/python3.6/dist-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in download.file(paste(file.path(url, i), "tool=geoquery", sep = "?"),  : 
  download from 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE42nnn/GSE42861/suppl//GSE42861_non-methylated_signal_matrix_SUBSETS.tar.gz?tool=geoquery' failed



```

**Comment by jlevy44** [comment]
My guess is that the download of the supplemental files are too big for:
```
geo.getGEOSuppFiles(query)
```
Try instead running this in R within the docker container and let me know if there are errors:
```
R
library(GEOquery)
getGEOSuppFiles("GSE42861")
```
If you are getting an error here, then the problem would appear to be with the R package. If not, we can continue to investigate what is going wrong and I can push a Docker update.

If possible, can you move this issue to PyMethylProcess: https://github.com/Christensen-Lab-Dartmouth/PyMethylProcess, thanks!

**Comment by jlevy44** [comment]
You may also want to look into this option:
https://github.com/Christensen-Lab-Dartmouth/PyMethylProcess/blob/master/pymethylprocess/utils.py#L37
